# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:        Hongyuan Huang
subtitle:     "\"\\x48\\x48\\x59\\x26\\x48\\x58\\x59\\x3A\\x44\""
description:  Hongyuan Huang's personal blog.
keywords:     example github jekyll features
language:     "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:      "" # the subpath of your site, e.g. /blog
url:          "http://HongyuanH.github.io/blog" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:    /blog/:categories/:title
cover:        /assets/cover.jpg

max_recent_posts: 5

# Build settings
incremental: false
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from